# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10kMsRGXVjACXMCc_UD7W2hCyJHGCMW6r
"""

import streamlit as st
 
st.title("Multiplication App using Streamlit")
 
# creates a horizontal line
st.write("---")

num1 = st.number_input(label="Enter first number")
num2 = st.number_input(label="Enter second number")

ans = 0
 
def calculate():
  ans = num1 * num2
  st.success(f"Answer = {ans}")

if st.button("Calculate result"):
    calculate()
